apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  elasticsearch.yml: |
    node.name: ${HOSTNAME}
    cluster.name: elasticsearch-cluster
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts: esnode-0.es-cluster-node.default.svc.cluster.local,esnode-1.es-cluster-node.default.svc.cluster.local,esnode-2.es-cluster-node.default.svc.cluster.local
    discovery.zen.minimum_master_nodes: 1
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    http.cors.enabled: true
    http.cors.allow-origin: "*"
